name: Generate notifications release
on:
  pull_request:
    types: [closed]
    branches: [main]

env:
  PLUGIN_NAME: whmcs-whatsapp-api-notifications
  WORK_DIR: src
  COMPOSER_JSON_PATH: modules/addons/lknhooknotification
  PHP_VERSION: "8.1"

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      # Cria estrutura correta do plugin
      - name: Organize plugin files
        working-directory: ${{ env.WORK_DIR }}
        run: |
          mkdir -p $PLUGIN_NAME
          mv modules $PLUGIN_NAME/
          ls -lah $PLUGIN_NAME

      # Cache do Composer
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      # Instala dependências via Composer no caminho correto
      - name: Composer install
        uses: php-actions/composer@v6
        with:
          php_version: ${{ env.PHP_VERSION }}
          working_dir: ${{ env.WORK_DIR }}/${{ env.PLUGIN_NAME }}/${{ env.COMPOSER_JSON_PATH }}
          args: --ignore-platform-reqs
          command: install
          dev: no

      # Compacta plugin
      - name: Archive plugin
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          path: ${{ env.PLUGIN_NAME }}
          directory: ${{ env.WORK_DIR }}
          filename: ${{ env.PLUGIN_NAME }}.zip
          exclusions: "*.git* .github"

      # Define a versão e cria uma nova tag (opcional: definir custom_tag)
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # custom_tag: "4.3.3"

      # Gera release com o artefato .zip
      - name: Generate GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.WORK_DIR }}/${{ env.PLUGIN_NAME }}.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: "main"
          draft: true
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
